### ISSUE TITLE
Aniyomi Resets tracking status of preset entries

### ISSUE THREAD

**Issue by AbdullahMehiz** [jmir1/aniyomi#239]
### Steps to reproduce

1. Add a manga/anime to the library
2. Have an account at a tracking service thats connected to the app and also have the entry inside of that account's list on a category other than watching/reading
3. Start tracking the aniyomi entry in the app

### Expected behavior

The entry tracking status should be the same as the one set by the user on his account like shown in this vid: [Tachiyomi](https://streamable.com/rc5ohb) & [TachiyomiJ2K](https://streamable.com/luc0ps) both respect the preset status on the user's account: 

### Actual behavior

Aniyomi RESETS the Tracking status of entries to Watching or reading eather than checking and using the status the user had on his account:
So instead of the status being paused, it got reset to reading
This happens both in [Anime](https://streamable.com/jd2ksl) and [Manga](https://streamable.com/75fpgg) 

### Aniyomi version

0.12.3.4

### Android version

Android 11

### Device

Xiaomi Redmi Note 8 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.4](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
i looked into the tachi code here: https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/Anilist.kt#L164-L167
and as you can see this is the intended behaviour. if you have read chapters, the app assumes you want to continue reading the manga right now and sets the status to reading. in your video, you have no chapters marked as read, so the app keeps the status from anilist.

you should probably open an issue in https://github.com/tachiyomiorg/tachiyomi if you don't like this "feature"
it does seem a bit nonsensical to me...

**Comment by Elecee** [comment]
A problem with the extension manga nine.. no chapters foundSent from my Samsung Galaxy smartphone.
-------- Original message --------From: jmir1 ***@***.***> Date: 24/11/2021  06:08  (GMT+04:00) To: jmir1/aniyomi ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [jmir1/aniyomi] Aniyomi Resets tracking status of preset entries (Issue #239) 
Closed #239.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/jmir1/aniyomi/issues/239#event-5663987257",
"url": "https://github.com/jmir1/aniyomi/issues/239#event-5663987257",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Elecee** [comment]
Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: jmir1 ***@***.***> Date: 24/11/2021  06:08  (GMT+04:00) To: jmir1/aniyomi ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [jmir1/aniyomi] Aniyomi Resets tracking status of preset entries (Issue #239) 
Closed #239.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/jmir1/aniyomi/issues/239#event-5663987257",
"url": "https://github.com/jmir1/aniyomi/issues/239#event-5663987257",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
