### ISSUE TITLE
Add Simkl Tracking 

### ISSUE THREAD

**Issue by AxharKhan** [jmir1/aniyomi#616]
### Describe your suggested feature

Since you guys have added sflix and other services that provide non anime entries. It would be best if the application had simkl.com tracking too. I like that service a lot and it would be very helpful if this was included.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.6](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by masyk** [comment]
Looks like beta now has Simkl tracker https://github.com/jmir1/aniyomi-mpv-beta/releases/tag/r4975

**Comment by AxharKhan** [comment]
Ok thank you.
